### ISSUE TITLE
DOS plotter

### ISSUE THREAD

**Issue by FPrith** [kumagai-group/vise#14]
I have fundamental questions on the DOS plotter implemented in vise.

According to "Tutorial – Calculations of various properties" in the vise homepage,
https://kumagai-group.github.io/vise/tutorial_properties.html
to my knowledge, the default command "vise pd" creates a total DOS plot and LDOS plots distinguished by their Wychoff positions.
In addition, color-coded PDOS are also plotted.

Is it possible to do the following three treatments in our command line?
1) Combine LDOS as one plot per element.
For example, for a Na-containing cell with three Wychoff positions of Na, is there a command to create a "summarized" Na LDOS plot?

2) Change the "Energy (eV)" range and the "Dos (1/eV)" range.
For example, is there a command to extend the lower limit of the energy range from -5 to -10?

3) Clear the legends (or change their positions) in a DOS plot.

**Comment by yuuukuma** [comment]
Thank you for your suggestion. I try to consider these when I can spare enough time for the update.

**Comment by FPrith** [comment]
Thank you very much for reply.
I will do calculations related to DOS and band dispersion and check/learn the relation between the INCAR tags specified by vise and VASP results.
